[WIP] Document mutation type #50
pimcore/data-hub pull request #262
Opened 2020-09-01 09:08 UTC by weisswurstkanone

proposal: not feature complete

2020-09-01 09:53 UTC, weisswurstkanone commented
Feedback is warmly appreciated!

2020-09-17 07:32 UTC, weisswurstkanone commented
TODO: consider https://github.com/pimcore/pimcore/issues/6892

2020-09-25 20:05 UTC, fashxp requested changes

2020-09-28 07:01 UTC, weisswurstkanone commented on doc/graphl/DocumentMutations.md
> +   updateDocumentPage(
existing editables are untouched. if you want to remove them you have to null them out explicitely. maybe introduce a 'replace' flag similar to the tree API ?

2020-09-28 07:04 UTC, weisswurstkanone commented on doc/graphl/DocumentMutations.md
> +   updateDocumentPage(
This would require that the schema generator first parses all the templates ?

2020-09-28 13:52 UTC, fashxp commented on doc/graphl/DocumentMutations.md
> +   updateDocumentPage(
not possible to generate schema for this case

2020-09-28 13:59 UTC, fashxp approved these changes

2020-09-29 10:34 UTC, merged