Setup PhpStan
pimcore/data-hub pull request #449
Opened 2021-12-16 18:59 UTC by blankse

2021-12-16 19:59 UTC, solverat commented
Crazy. I would also suggest removing the `Class constructor.` annotation like here (https://github.com/pimcore/data-hub/blob/c9690a0b98919d4e219f7496806c5e58ab3de9c0/src/Event/GraphQL/Model/QueryTypeEvent.php#L92).

2021-12-17 08:20 UTC, blankse commented on src/GraphQL/Helper.php
>                          if (isset($fieldMappingTable, $key)) {
@fashxp Can you explain whats the purpose here? Should it be in_array or something?

2021-12-17 09:11 UTC, blankse commented
@solverat Removed this solverat

2021-12-17 14:58 UTC, blankse commented on src/GraphQL/Helper.php
>                          if (isset($fieldMappingTable, $key)) {
I think this must be right: https://github.com/pimcore/data-hub/pull/449/commits/75844da03124e65dc8077d3c06f53e17ee2e3cc6

2022-01-05 11:42 UTC, blankse commented
@fashxp https://github.com/pimcore/data-importer/pull/141 is locked, so I can't write there. I changed the PR according to your suggestions.

2022-01-10 13:21 UTC, fashxp requested changes

2022-01-10 13:21 UTC, fashxp commented on src/GraphQL/DataObjectQueryFieldConfigGenerator/Helper/ObjectsMetadata.php
> +            /** @var ElementMetadata $relation */
shouldn't that be ObjectMetadata?

2022-01-10 13:21 UTC, fashxp commented on src/GraphQL/Resolver/QueryType.php
> +    public function resolveEdge($value, $args = [], $context = [], ResolveInfo $resolveInfo = null)
change of signature ... should we really do that here?

2022-01-10 13:21 UTC, fashxp commented on src/GraphQL/Resolver/QueryType.php
> +    public function resolveEdges($value, $args = [], $context = [], ResolveInfo $resolveInfo = null)
change of signature ... should we really do that here?

2022-01-10 13:21 UTC, fashxp commented on src/Migrations/Version20190614135736.php
> +use Doctrine\Migrations\AbstractMigration;
don't change that, these are the Pimcore 6.9 migrations ... we could remove them

2022-01-10 13:21 UTC, fashxp commented on src/Migrations/Version20190904131554.php
> +use Doctrine\Migrations\AbstractMigration;
don't change that, these are the Pimcore 6.9 migrations ... we could remove them

2022-01-10 13:21 UTC, fashxp commented on src/Migrations/Version20210305134111.php
> +use Doctrine\Migrations\AbstractMigration;
don't change that, these are the Pimcore 6.9 migrations ... we could remove them

2022-01-10 13:21 UTC, fashxp commented on src/Migrations/Version20211110093612.php
> +use Doctrine\Migrations\AbstractMigration;
don't change that, these are the Pimcore 6.9 migrations ... we could remove them

2022-01-10 13:21 UTC, fashxp commented on src/Service/FileUploadService.php
> -        if (null === $bodyParams) {
why remove that? since this is additional information for the user.

2022-01-10 13:21 UTC, fashxp commented on src/Service/OutputCacheService.php
> -
why remove that?

2022-01-10 18:50 UTC, blankse commented on src/GraphQL/DataObjectQueryFieldConfigGenerator/Helper/ObjectsMetadata.php
> +            /** @var ElementMetadata $relation */
Fixed: https://github.com/pimcore/data-hub/pull/449/commits/60cead51fbabf0375522f19a805ca37ad1bb5d3d

2022-01-10 18:54 UTC, blankse commented on src/GraphQL/Resolver/QueryType.php
> +    public function resolveEdge($value, $args = [], $context = [], ResolveInfo $resolveInfo = null)
Reverted: https://github.com/pimcore/data-hub/pull/449/commits/d52aa80d882f8f4ca59c2a1156f6777de6eee1cd

2022-01-10 18:55 UTC, blankse commented on src/GraphQL/Resolver/QueryType.php
> +    public function resolveEdges($value, $args = [], $context = [], ResolveInfo $resolveInfo = null)
Reverted: https://github.com/pimcore/data-hub/pull/449/commits/6e6ba59ce38a56f3b4a67cb6e4a2dccbc9308e7b

2022-01-10 18:58 UTC, blankse commented on src/Migrations/Version20190614135736.php
> +use Doctrine\Migrations\AbstractMigration;
Removed the migrations in https://github.com/pimcore/data-hub/pull/449/commits/142d8f90d7293d3fcd26ecd37c7ead8340c9cf0e

2022-01-10 18:58 UTC, blankse commented on src/Migrations/Version20190904131554.php
> +use Doctrine\Migrations\AbstractMigration;
Removed the migrations in https://github.com/pimcore/data-hub/pull/449/commits/142d8f90d7293d3fcd26ecd37c7ead8340c9cf0e

2022-01-10 18:58 UTC, blankse commented on src/Migrations/Version20210305134111.php
> +use Doctrine\Migrations\AbstractMigration;
Removed the migrations in https://github.com/pimcore/data-hub/pull/449/commits/142d8f90d7293d3fcd26ecd37c7ead8340c9cf0e

2022-01-10 18:58 UTC, blankse commented on src/Migrations/Version20211110093612.php
> +use Doctrine\Migrations\AbstractMigration;
Removed the migrations in https://github.com/pimcore/data-hub/pull/449/commits/142d8f90d7293d3fcd26ecd37c7ead8340c9cf0e

2022-01-10 19:01 UTC, blankse commented on src/Service/FileUploadService.php
> -        if (null === $bodyParams) {
@fashxp `$bodyParams = $request->request->all();` must be an array. Has an array return type hint.

2022-01-10 19:05 UTC, blankse commented on src/Service/OutputCacheService.php
> -
@fashxp There is no config in src/DependencyInjection/Configuration.php and no exclude_pattern property in this class. This property also not used anywhere.

2022-01-11 08:35 UTC, fashxp approved these changes

2022-01-11 08:36 UTC, fashxp commented
@blankse thx very much!! 
We will review changes once more and then we are ready to merge

2022-01-18 10:53 UTC, blankse commented
@fashxp Can you merge 1.1 branch to 1.x? So I can rebase/merge this.

2022-01-18 11:10 UTC, weisswurstkanone commented
done

2022-01-19 07:39 UTC, weisswurstkanone commented
@blankse , awesome ! Can we add a section in the docs on how to run this on a local instance? Similar to https://pimcore.com/docs/pimcore/current/Development_Documentation/Development_Tools_and_Details/Testing/Core_Tests.html

Would be great!

2022-01-19 09:49 UTC, blankse commented
@weisswurstkanone I add an doc page for it.

2022-01-24 14:21 UTC, weisswurstkanone commented
@blankse What is the best practice for generating and checking in the baseline? I assume that you created the original one on your local instance?

2022-01-24 14:28 UTC, blankse commented
@weisswurstkanone Yes I generated it via:
`vendor/bin/phpstan analyse --memory-limit=-1 --generate-baseline`
Maybe we can add the new baseline file as artifact to the github action:
https://docs.github.com/en/actions/advanced-guides/storing-workflow-data-as-artifacts

2022-01-24 14:33 UTC, weisswurstkanone commented
yep, that would be nice

2022-01-24 14:50 UTC, weisswurstkanone commented
Great, thanks a lot!

2022-01-24 14:50 UTC, merged

2022-01-24 15:01 UTC, blankse commented
> yep, that would be nice

@weisswurstkanone I can test it in a new PR :)

2022-01-24 15:02 UTC, weisswurstkanone commented
wonderful!