Add QueryType for Version on Assets
pimcore/data-hub pull request #838
Opened 2024-02-25 13:31 UTC by leitge

2024-04-05 09:33 UTC, Corepex requested changes
@leitge, thanks for your PR. 
Tested it - looks good to me :) just one (very picky) thing to make the IDE happy :rofl:

2024-04-05 09:33 UTC, Corepex commented on src/GraphQL/Resolver/AssetType.php
> +    public function resolveVersion($value = null, $args = [], $context = [], ResolveInfo $resolveInfo = null)
```suggestion
     /**
     * @throws Exception
     */
    public function resolveVersion($value = null, $args = [], $context = [], ResolveInfo $resolveInfo = null)
```

2024-05-03 08:20 UTC, Corepex commented
@leitge friendly reminder :alarm_clock: :lollipop:

2024-05-03 08:24 UTC, leitge reviewed
adjusted

2024-05-03 08:24 UTC, leitge commented
@Corepex done ;)

2024-05-03 08:31 UTC, Corepex approved these changes
LGTM - thanks @leitge for your PR. 
Great to actively work with you on data-hub :100:

2024-05-03 08:31 UTC, merged